FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Clear Junction

Simple API.agpaokgpoaskgpo

## Booking [/api/booking]

### Reservation [POST /api/booking/iban]

+ Request IBAN Consumer Reservation (application/json)
    + Body

            {
                "header": {
                    "apiVer": "0.6",
                    "apiToken": "uuid",
                    "requestTime": "2017-06-22T11:40:51.620Z",
                    "requestSignature": "xxxxxxxxxxxxxxxxxxxxxxxx (sha512)",
                    "apiKey": "xxxxxxxxxxxxxxxx"
                },
                "body": {
                    "data": {
                        "consumer": {
                            "merchantUuid": "2e2ccab8-19ad-40c6-a8ac-411a23645404",
                            "merchantCustomerIdentificator": "c4b78t34qb678034qpn",
                            "firstName": "John",
                            "lastName": "Doe",
                            "localFirstName": "John",
                            "localLastName": "Doe",
                            "email": "john.doe@gmail.com",
                            "document": [{
                                "type": "passport|driver",
                                "number": "AE111111",
                                "issuedCountryCode": "USA",
                                "issuedBy": "Антовоский РВДГУУМВД г.НьюЙорк",
                                "issuedDate": "20170622"
                            }],
                            "gender": "male:female:other",
                            "phoneNumber": "972541122334",
                            "dateOfBirth": "20170222",
                            "billingAddress": "Some billing address",
                            "customInfo": {
                                "It's only for example": "JSON",
                                "incorporationDate": "22/12/2010",
                                "divisionType": "Delivery",
                                "divisionId": "10"
                            }
                        }
                    }
                }
            }

+ Response 200 (application/json)

        {
            "header": {
                "apiVer": "0.6",
                "responseTime": "2017-06-22T11:40:51.620Z"
            },
            "body":{
                "data": {
                    "consumer": {
                        "merchantUuid": "2e2ccab8-19ad-40c6-a8ac-411a23645404",
                        "merchantCustomerIdentificator": "c4b78t34qb678034qpn",
                        "firstName": "John",
                        "lastName": "Doe",
                        "localFirstName": "John",
                        "localLastName": "Doe",
                        "email": "john.doe@gmail.com",
                        "document": [{
                            "type": "passport|driver",
                            "number": "AE111111",
                            "issuedCountryCode": "USA",
                            "issuedBy": "Антовоский РВДГУУМВД г.НьюЙорк",
                            "issuedDate": "20170622"
                        }],
                        "gender": "male:female:other",
                        "phoneNumber": "972541122334",
                        "dateOfBirth": "20170222",
                        "billingAddress": "Some billing address",
                        "customInfo": {
                            "It's only for example": "JSON",
                            "incorporationDate": "22/12/2010",
                            "divisionType": "Delivery",
                            "divisionId": "10"
                        }
                    },
                    "virtualIban": "xxxxxxxxxxxxx"
                },
                "errors": null
            }
        }
        
+ Response 401 (application/json)

        {
            "header": {
                "apiVer": "0.6",
                "responseTime": "2017-06-22T11:40:51.620Z"
            },
            "body": {
                "data": null,
                "errors": [{
                    "error": {
                        "errorCode": 404,
                        "errorDescription":  "title: This field is required. email: The provided value is invalid"
                    },
                    "processorError": {
                        "errorCode": 404,
                        "errorDescription": "Error validation"
                    }
                }]
            }
        }